version: '2'

services:
  fillager:
    image: fillager
    ports:
      - "80"
    build:
      context: ./Fillager
      dockerfile: Dockerfile

  reverseproxy:
    image: nginx:latest
    ports:
      - "8080"
    volumes:
      - ./code:/srv/ngin/
    command: sh srv/ngin/post-run-copy.sh


  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: 6b4535c9d0545e036d5b
      MINIO_SECRET_KEY: f50a73124f5699570beb9ad44cd941
    command: server /export

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: somedb
      MYSQL_USER: someuser
      MYSQL_PASSWORD: very_secret