version: '2'

services:
  fillager:
    image: fillager
    environment:
      RABBITMQ_BACKUP_QUEUE: backup-queue-rabbitmq
    ports:
      - "80"
    build:
      context: ./Fillager
      dockerfile: Dockerfile

  identity-redis:
    image: redis


  reverseproxy:
    image: nginx:latest
    ports:
      - "8080"
    volumes:
      - ./code:/srv/ngin/
    command: sh srv/ngin/post-run-copy.sh


  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: 6b4535c9d0545e036d5b
      MINIO_SECRET_KEY: f50a73124f5699570beb9ad44cd941
    command: server http://minio/export1 http://minio/export2 http://minio2/export1 http://minio2/export2

  minio2:
    image: minio/minio
    environment: 
      MINIO_ACCESS_KEY: 6b4535c9d0545e036d5b
      MINIO_SECRET_KEY: f50a73124f5699570beb9ad44cd941
    command: server http://minio/export1 http://minio/export2 http://minio2/export1 http://minio2/export2

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: somedb
      MYSQL_USER: someuser
      MYSQL_PASSWORD: very_secret

  backup-queue-rabbitmq:
    image: rabbitmq:latest
    hostname: backup-queue-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    ports:
        - "5672:5672"
